language: objective-c
osx_image: xcode9.3

branches:
 only:
 - master

script:
- xcodebuild clean build -sdk iphonesimulator -project KASlideShow.xcodeproj -scheme KASlideShow CODE_SIGNING_REQUIRED=NO
